scenario: # 场景
  type: 2 # 类型，0：循迹，1：静态绕障，2：同一车道上的障碍物交互，包括停障，跟车，超车，会车， 3：动态避障
  obs_num: 1 # 障碍物数量


# 类型备注：
# 0-循迹：障碍物数量0；两个模型都隐藏
# 1-静态绕障：障碍物数量3；静态模型，在 src/planning/urdf/obs_car/obs_car.xacro 位置
# 2-交互：障碍物数量1；动态模型
# 3-动态避障：障碍物数量3；动态模型
